### ISSUE TITLE
Download Fail

### ISSUE THREAD

**Issue by AymenRc** [cetra3/onlyoffice-alfresco#17]
Hello guys, I have been stuck in this problem for 5days now and could not fin any solution on the internet, I tried multiple fixes and still the same issue.

Here is the converted/out.log 

`[ERROR] nodeJS - error downloadFile:url=http://127.0.0.1:8080/alfresco/s/api/node/content/workspace/SpacesStore/8bf565f6-133c-423f-8155-9e1ca3db4ac6?alf_ticket=TICKET_b96f08d410e728ec47993f1b1c7b4f5cbed4ff1e;attempt=2;code:undefined;connect:undefined;(id=8bf565f6-133c-423f-8155-9e1ca3db4ac6_20180522154625)
Error: Error response: statusCode:404 ;body:
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<title>Error</title>
</head>
<body>
<pre>Cannot GET /alfresco/s/api/node/content/workspace/SpacesStore/8bf565f6-133c-423f-8155-9e1ca3db4ac6</pre>
</body>
</html>

    at Request._callback (/var/www/onlyoffice/documentserver/server/Common/sources/utils.js:249:18)
    at Request.self.callback (/var/www/onlyoffice/documentserver/server/Common/node_modules/request/request.js:186:22)
    at emitTwo (events.js:106:13)
    at Request.emit (events.js:191:7)
    at Request.<anonymous> (/var/www/onlyoffice/documentserver/server/Common/node_modules/request/request.js:1163:10)
    at emitOne (events.js:96:13)
    at Request.emit (events.js:188:7)
    at IncomingMessage.<anonymous> (/var/www/onlyoffice/documentserver/server/Common/node_modules/request/request.js:1085:12)
    at IncomingMessage.g (events.js:292:16)
    at emitNone (events.js:91:20)
[2018-05-24 13:45:14.959] [ERROR] nodeJS - error downloadFile:url=http://127.0.0.1:8080/alfresco/s/api/node/content/workspace/SpacesStore/8bf565f6-133c-423f-8155-9e1ca3db4ac6?alf_ticket=TICKET_b96f08d410e728ec47993f1b1c7b4f5cbed4ff1e;attempt=3;code:undefined;connect:undefined;(id=8bf565f6-133c-423f-8155-9e1ca3db4ac6_20180522154625)
Error: Error response: statusCode:404 ;body:
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<title>Error</title>
</head>
<body>
<pre>Cannot GET /alfresco/s/api/node/content/workspace/SpacesStore/8bf565f6-133c-423f-8155-9e1ca3db4ac6</pre>
</body>
</html>

    at Request._callback (/var/www/onlyoffice/documentserver/server/Common/sources/utils.js:249:18)
    at Request.self.callback (/var/www/onlyoffice/documentserver/server/Common/node_modules/request/request.js:186:22)
    at emitTwo (events.js:106:13)
    at Request.emit (events.js:191:7)
    at Request.<anonymous> (/var/www/onlyoffice/documentserver/server/Common/node_modules/request/request.js:1163:10)
    at emitOne (events.js:96:13)
    at Request.emit (events.js:188:7)
    at IncomingMessage.<anonymous> (/var/www/onlyoffice/documentserver/server/Common/node_modules/request/request.js:1085:12)
    at IncomingMessage.g (events.js:292:16)
    at emitNone (events.js:91:20)`

It will be really great if you could help me! 

Thank you :)

**Comment by cetra3** [comment]
Hi @AymenRc looks like you haven't updated your sysadmin params.

OnlyOffice will make the connection to Alfresco on behalf of the client, so OnlyOffice needs to be able to talk to Alfresco. In order for OnlyOffice to do this, Alfresco needs to generate what it thinks the external URL is. Make sure that the following properties are set correctly in alfresco-global.properties

```
alfresco.protocol=http
alfresco.host=alfresco.yourcompany.local
alfresco.port=8080
alfresco.context=alfresco
```

**Comment by AymenRc** [comment]
Hey @cetra3 thank you for your answer !
I think that I need further help, since I am working on a VM so it is a localhost and I have those parameters in global properties : `alfresco.protocol=http
alfresco.host=127.0.0.1
alfresco.port=8080
alfresco.context=alfresco`

Isn't that supposed to be the correct alfresco.host or what should I put there? 

## I tried to:
Notice that I tried to put this `alfresco.host=alfresco.yourcompany.local` as it is and when I tried I first get an error saying `The file cannot be accessed right now`  the message was shown like about 3sec and when I refresh it appears less than a second you cant even read it! And then I get the warning `The document could not be saved.Please check the connection settings or contact your administrator. When you click the OK button you will be prompted to download the document `
and when I click OK nothing happens.

Now when I Check the converter/out.log I get this

`   at Request.emit (events.js:188:7)
    at IncomingMessage.<anonymous> (/var/www/onlyoffice/documentserver/server/Common/node_modules/request/request.js:1085:12)
    at IncomingMessage.g (events.js:292:16)
    at emitNone (events.js:91:20)
[2018-05-25 09:02:51.216] [WARN] nodeJS - update cluster with 1 workers
[2018-05-25 09:02:51.270] [WARN] nodeJS - worker 613 started.
[2018-05-25 09:02:51.272] [WARN] nodeJS - update cluster with 1 workers
[2018-05-25 09:04:13.581] [WARN] nodeJS - update cluster with 1 workers
[2018-05-25 09:04:13.663] [WARN] nodeJS - worker 707 started.
[2018-05-25 09:04:13.664] [WARN] nodeJS - update cluster with 1 workers`

Thank you!

**Comment by cetra3** [comment]
@AymenRc you will need to ensure that both onlyoffice and alfresco can talk to eachother and resolve eachother's addresses, even if it's in a local VM network, they will need to be addressable via DNS.

This is something that we can help with on a [supported subscription](https://www.parashift.com.au/add-ons/), but it doesn't look like an error with the module itself
