### ISSUE TITLE
Not opening documents of size more than 100mb.

### ISSUE THREAD

**Issue by monicakumari** [cetra3/onlyoffice-alfresco#29]
Hi, 
Onlyoffice is working great. But I am having an issue that its **not opening documents of size more than 100 mb**, even if its 101 mb file. 
getting "**download failed**" message on preview page and below error on the console :

`Caused by: org.alfresco.repo.content.transform.UnsupportedTransformationException: 09230030 Unsupported transformation: transformer.OpenOffice.2Pdf application/vnd.openxmlformats-officedocument.presentationml.presentation to application/pdf 
    at org.alfresco.repo.content.transform.AbstractContentTransformer2.checkTransformable(AbstractContentTransformer2.java:188)
    at org.alfresco.repo.content.transform.AbstractContentTransformer2.transform(AbstractContentTransformer2.java:258)
    at org.alfresco.repo.content.transform.ComplexContentTransformer.transformInternal(ComplexContentTransformer.java:492)
    at org.alfresco.repo.content.transform.AbstractContentTransformer2.transform(AbstractContentTransformer2.java:272)
    at org.alfresco.repo.content.ContentServiceImpl.failoverTransformers(ContentServiceImpl.java:668)
    at org.alfresco.repo.content.ContentServiceImpl.transform(ContentServiceImpl.java:617)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:317)
    at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:183)
    at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:150)
    at net.sf.acegisecurity.intercept.method.aopalliance.MethodSecurityInterceptor.invoke(MethodSecurityInterceptor.java:80)
    at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:172)
    at org.alfresco.repo.model.ml.MLContentInterceptor.invoke(MLContentInterceptor.java:136)
    at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:172)
    at org.alfresco.repo.security.permissions.impl.ExceptionTranslatorMethodInterceptor.invoke(ExceptionTranslatorMethodInterceptor.java:53)
    at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:172)
    at org.alfresco.repo.audit.AuditMethodInterceptor.proceedWithAudit(AuditMethodInterceptor.java:256)
    at org.alfresco.repo.audit.AuditMethodInterceptor.proceed(AuditMethodInterceptor.java:216)
    at org.alfresco.repo.audit.AuditMethodInterceptor.invoke(AuditMethodInterceptor.java:171)
    at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:172)
    at org.springframework.transaction.interceptor.TransactionInterceptor$1.proceedWithInvocation(TransactionInterceptor.java:96)
    at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:260)
    at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:94)
    at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:172)
    at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:204)
    at com.sun.proxy.$Proxy55.transform(Unknown Source)
    at org.alfresco.repo.rendition.executer.AbstractTransformationRenderingEngine$TransformationCallable$1.doWork(AbstractTransformationRenderingEngine.java:447)
    ... 8 more`

I have tried by adding the below properties in alfresco-global.properties file but not worked.
`onlyoffice.preview.document.size.threshold=1048576000
onlyoffice.preview.pptx.threshold=1000000
onlyoffice.preview.ppt.threshold=1000000
onlyoffice.transformer.OpenOffice.2Pdf.available=true
onlyoffice.transformer.OpenOffice.2Pdf.extensions.pptx.pdf.supported=true`

Anybody have any idea, how to preview files of size more than 100 or 200 mb r how to increase the timout size or something. ?
Please guide.

Thanks.

**Comment by sergefedorow** [comment]
Hi! As I understand you'v got transformer.OpenOffice.2Pdf error. But this cetra3 connector makes transformation by onlyofffice document server, not Openoffice. Are you sure that you use catra3 connector, not forked onlyoffice connector?

**Comment by monicakumari** [comment]
I have download amps from https://github.com/cetra3/onlyoffice-alfresco/releases and applied on alfresco's instance.
and a seperate server for docker-onlyoffice using https://github.com/ONLYOFFICE/Docker-DocumentServer.

**Comment by sergefedorow** [comment]
I checked, both connectors can't open files more then 100MB. I think it's a DocumentServer limitation. I can download 107MB file from alfresco to office server in command line by callback file URL. But DocumentServer gives "Download Failed" error. [Troubleshooting](https://api.onlyoffice.com/editors/troubleshooting#download) of this error say about document.link problems. But it's work.
Related [issue #470 is closed](https://github.com/ONLYOFFICE/DocumentServer/issues/470).
Even so, I think you should ask Onlyoffice support directly.

**Comment by cetra3** [comment]
There aren't any inherent limits in the preview unless you turn the preview limits on.  Even then they only effect whether the preview displays or not within the browser window, rather than whether the document server can download it.

The setting you want to change is in the documentserver config, normally located here (inside the docker image):

```
/etc/onlyoffice/documentserver/default.json
```

Look for the `FileConverter` section and change the `maxDownloadBytes` value:

```
...
        "FileConverter": {
                "converter": {
                        "maxDownloadBytes": 104857600,
                        "downloadTimeout": {
                                "connectionAndInactivity": "10s",
                                "wholeCycle": "2m"
                        },
....
```

As this is not an issue with this module I will close this issue.

**Comment by monicakumari** [comment]
Thank you for your help. I have tried but increasing or decreasing the value for "maxDownloadBytes"
has no effect. Is there anything else I can try ?

**Comment by sergefedorow** [comment]
Monica, open issue at https://github.com/ONLYOFFICE/DocumentServer/issues.
