### ISSUE TITLE
Not compatible with Alfresco CE5.0.x ?

### ISSUE THREAD

**Issue by cetra3** [cetra3/onlyoffice-alfresco#9]
_From @ttownsend on December 19, 2015 22:4_

Hi - this looks like a good add-on, but it's not functional on a completely stock Alfresco CE 5.0 install.
Tomcat throws this:
2015-12-19 12:24:40,340  ERROR [web.context.ContextLoader] [localhost-startStop-1] Context initialization failed
 org.springframework.beans.factory.CannotLoadBeanClassException: Error loading class [com.parashift.onlyoffice.CallBack] for bean with name 'webscript.onlyoffice.callback.post' defined in URL [jar:file:/opt/alfresco-5.0.c/tomcat/webapps/alfresco/WEB-INF/lib/onlyoffice-alfresco-repo-1.0.2.jar!/com/parashift/onlyoffice/CallBack.class]: problem with class file or dependent class; nested exception is java.lang.UnsupportedClassVersionError: com/parashift/onlyoffice/CallBack : Unsupported major.minor version 52.0 (unable to load class com.parashift.onlyoffice.CallBack)
        at org.springframework.beans.factory.support.AbstractBeanFactory.resolveBeanClass(AbstractBeanFactory.java:1281)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.predictBeanType(AbstractAutowireCapableBeanFactory.java:575)
        at org.springframework.beans.factory.support.AbstractBeanFactory.isFactoryBean(AbstractBeanFactory.java:1347)
        at org.springframework.beans.factory.support.AbstractBeanFactory.isFactoryBean(AbstractBeanFactory.java:913)
        at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:614)
        at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:932)
        at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:479)
        at org.springframework.web.context.ContextLoader.configureAndRefreshWebApplicationContext(ContextLoader.java:410)
        at org.springframework.web.context.ContextLoader.initWebApplicationContext(ContextLoader.java:306)
        at org.springframework.web.context.ContextLoaderListener.contextInitialized(ContextLoaderListener.java:112)
        at org.alfresco.web.app.ContextLoaderListener.contextInitialized(ContextLoaderListener.java:63)
        at org.apache.catalina.core.StandardContext.listenerStart(StandardContext.java:4973)
        at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5467)
        at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:150)
        at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:901)
        at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:877)
        at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:632)
        at org.apache.catalina.startup.HostConfig.deployWAR(HostConfig.java:1073)
        at org.apache.catalina.startup.HostConfig$DeployWar.run(HostConfig.java:1857)
        at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
        at java.util.concurrent.FutureTask.run(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at java.lang.Thread.run(Unknown Source)
Caused by: java.lang.UnsupportedClassVersionError: com/parashift/onlyoffice/CallBack : Unsupported major.minor version 52.0 (unable to load class com.parashift.onlyoffice.CallBack)
        at org.apache.catalina.loader.WebappClassLoader.findClassInternal(WebappClassLoader.java:2961)
        at org.apache.catalina.loader.WebappClassLoader.findClass(WebappClassLoader.java:1210)
        at org.apache.catalina.loader.WebappClassLoader.loadClass(WebappClassLoader.java:1690)
        at org.apache.catalina.loader.WebappClassLoader.loadClass(WebappClassLoader.java:1571)
        at org.springframework.util.ClassUtils.forName(ClassUtils.java:266)
        at org.springframework.beans.factory.support.AbstractBeanDefinition.resolveBeanClass(AbstractBeanDefinition.java:419)
        at org.springframework.beans.factory.support.AbstractBeanFactory.doResolveBeanClass(AbstractBeanFactory.java:1299)
        at org.springframework.beans.factory.support.AbstractBeanFactory.resolveBeanClass(AbstractBeanFactory.java:1270)
        ... 23 more

_Copied from original issue: cetra3/etherpad-alfresco#9_

**Comment by cetra3** [comment]
Seems to be related to using Java 7 but compiling on Java 8.  

Will need to recompile the bundles on Java 7 and put in an explicit compatibility setting in `build.gradle`:

```
allprojects {
    sourceCompatibility = 1.7
    targetCompatibility = 1.7
}
```

**Comment by cetra3** [comment]
@ttownsend

Please download the latest version:
https://github.com/cetra3/onlyoffice-alfresco/releases/tag/1.0.3
